version: "2"
run:
  tests: true
output:
  formats:
    text:
      path: stdout
      print-issued-lines: false
linters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
